### ISSUE TITLE
Projet 6 OC

### ISSUE THREAD

**Issue by sofia-fal** [kyra110/kyra110#1]
Salut, je suis en plein P6 pour ma formation intégrateur web et tes vidéos m'aidaient beaucoup, mais j'ai vu que tu les avais supprimées. Ce serait possible de les remettre en ligne d'une façon ou d'une autre ? Merci. 😓

**Comment by kyra110** [comment]
Hello ! Je viens de voir ton message Normalement tout est revenu à la
normale 💪 Bonne Formation et merci de regarder les vidéos ☺️

**Comment by sofia-fal** [comment]
Merci beaucoup. :) Continue comme ça !
